[tool.poetry]
name = "simlify"
version = "0.0.0"
description = "Simplify your molecular simulation workflow."
authors = [
    "oasci <us@oasci.org>",
]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.7.2"
numpy = "^1.26.2"
scipy = "^1.11.4"
pydantic = "^2.7.1"
atomea = "^0.0.0.post158"
mdanalysis = "^2.7.0"

[tool.poetry.group.dev.dependencies]
black = "^23.9.0"
isort = "^5.12.0"
pre-commit = "^3.4.0"
pylint = "^2.17.5"
mypy = "^1.5.1"
mypy-extensions = "^1.0.0"
bump-my-version = "^0.11.0"
poetry-dynamic-versioning = "^1.1.0"
twine = "^5.0.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
pytest-cov = "^4.1.0"
pytest-html = "^4.0.1"
coverage = "^7.3.1"
colorama = "^0.4.6"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.5.3"
mkdocs-material = "^9.4.7"
material-plausible-plugin = "^0.2.0"
pymdown-extensions = "^10.3.1"
mkdocstrings = "^0.23.0"
mkdocstrings-python = "^1.7.3"
mkdocs-gen-files = "^0.5.0"
mkdocs-awesome-pages-plugin = "^2.9.2"

[tool.poetry.scripts]
simlify-pdb-filter = "simlify.structure.pdb.utils:cli_filter_pdb"
simlify-pdb-renumber = "simlify.structure.pdb.numbering.main:cli_unify_numbering"

[tool.bumpversion]
current_version = "0.0.0"
tag = true
commit = true

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
no_regex = false
search = "\\[Unreleased\\]"
replace = "[Unreleased]\n\n## [{new_version}] - {now:%Y-%m-%d}"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
format-jinja = "{%- if distance == 0 -%}{{ serialize_pep440(base) }}{%- else -%}{{ serialize_pep440(base, post=distance) }}{%- endif -%}"

[tool.poetry-dynamic-versioning.substitution]
patterns = [
    "(^__version__\\s*(?::.*?)?=\\s*['\"])[^'\"]*(['\"])",
]
folders = [
    { path = "conda_poetry_liaison" },
]

[tool.pylint.messages_control]
good-names = [
    "i",
    "j",
    "e",
    "ex",
]
ignore = [
    "CVS",
    "conf.py",
]

[tool.black]
target-version = [
    "py312",
]
line-length = 88
color = true
exclude = "/(\n    \\.git\n    | \\.hg\n    | \\.mypy_cache\n    | \\.tox\n    | \\.venv\n    | _build\n    | buck-out\n    | build\n    | dist\n    | env\n    | venv\n)/\n"

[tool.isort]
py_version = 312
line_length = 88
known_typing = [
    "typing",
    "types",
    "typing_extensions",
    "mypy",
    "mypy_extensions",
]
sections = [
    "FUTURE",
    "TYPING",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
profile = "black"
include_trailing_comma = true
multi_line_output = 3
indent = 4
color_output = true

[tool.mypy]
python_version = "3.12"
pretty = true
show_traceback = true
color_output = true
allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pytest.ini_options]
norecursedirs = [
    "simlify",
    "*.egg",
    ".eggs",
    "dist",
    "build",
    "docs",
    ".tox",
    ".git",
    "__pycache__",
]
doctest_optionflags = [
    "NUMBER",
    "NORMALIZE_WHITESPACE",
    "IGNORE_EXCEPTION_DETAIL",
]
addopts = [
    "--strict-markers",
    "--tb=short",
    "--doctest-modules",
    "--doctest-continue-on-failure",
]

[tool.coverage.run]
source = [
    "tests",
]

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "poetry-dynamic-versioning>=1.0.0,<2.0.0",
]
build-backend = "poetry_dynamic_versioning.backend"

[coverage.paths]
source = "simlify"

[coverage.run]
branch = true

[coverage.report]
fail_under = 50
show_missing = true

["tool.poetry.group.conda.dependencies"]
annotated-types = "^0.6.0"
appdirs = "^1.4.4"
Brotli = "^1.0.9"
build = "^1.2.1"
CacheControl = "^0.14.0"
cachy = "^0.3.0"
certifi = "^2024.6.2"
cffi = "^1.16.0"
cfgv = "^3.3.1"
charset-normalizer = "^2.0.4"
cleo = "^2.1.0"
click = "^8.1.7"
click-default-group = "^1.2.2"
clikit = "^0.6.2"
colorama = "^0.4.6"
conda_lock = "^2.5.6"
conda_poetry_liaison = "^0.1.2"
contourpy = "^1.2.1"
crashtest = "^0.4.1"
cryptography = "^42.0.5"
cycler = "^0.12.1"
distlib = "^0.3.8"
dulwich = "^0.21.3"
edgembar = "^0.2"
ensureconda = "^1.4.4"
fastjsonschema = "^2.19.1"
filelock = "^3.13.1"
fonttools = "^4.53.0"
gitdb = "^4.0.7"
GitPython = "^3.1.37"
html5lib = "^1.1"
identify = "^2.5.36"
idna = "^3.7"
importlib_metadata = "^7.1.0"
installer = "^0.7.0"
"jaraco.classes" = "^3.2.1"
jeepney = "^0.7.1"
Jinja2 = "^3.1.4"
joblib = "^1.4.2"
keyring = "^24.3.1"
kiwisolver = "^1.4.5"
MarkupSafe = "^2.1.3"
matplotlib = "^3.8.4"
"MMPBSA.py" = "^16.0"
more-itertools = "^10.1.0"
msgpack = "^1.0.3"
munkres = "^1.1.4"
ndfes = "^1.8"
nodeenv = "^1.9.1"
numpy = "^1.26.4"
packaging = "^23.2"
packmol_memgen = "^2024.2.9"
pandas = "^2.2.2"
ParmEd = "^4.2.2"
pastel = "^0.2.1"
pdb4amber = "^22.0"
pexpect = "^4.9.0"
pillow = "^10.3.0"
pip = "^24.0"
pkginfo = "^1.10.0"
platformdirs = "^3.10.0"
poetry = "^1.8.3"
poetry-core = "^1.9.0"
poetry-plugin-export = "^1.8.0"
pre_commit = "^3.7.1"
ptyprocess = "^0.7.0"
pycparser = "^2.21"
pydantic = "^2.5.3"
pydantic_core = "^2.14.6"
pylev = "^1.3.0"
pyMSMT = "^22.0"
pyOpenSSL = "^24.0.0"
pyparsing = "^3.1.2"
pyproject_hooks = "^1.1.0"
PySocks = "^1.7.1"
python-dateutil = "^2.9.0"
pytraj = "^2.0.6"
pytz = "^2024.1"
PyYAML = "^6.0.1"
rapidfuzz = "^3.5.2"
requests = "^2.32.2"
requests-toolbelt = "^1.0.0"
"ruamel.yaml" = "^0.17.21"
sander = "^22.0"
scipy = "^1.13.1"
SecretStorage = "^3.3.1"
setuptools = "^69.5.1"
shellingham = "^1.5.4"
six = "^1.16.0"
smmap = "^4.0.0"
tomli = "^2.0.1"
tomli_w = "^1.0.0"
tomlkit = "^0.12.5"
toolz = "^0.12.0"
trove-classifiers = "^2024.5.22"
typing_extensions = "^4.11.0"
tzdata = "^2024.1"
ukkonen = "^1.0.1"
urllib3 = "^1.26.18"
virtualenv = "^20.26.1"
webencodings = "^0.5.1"
wheel = "^0.43.0"
zipp = "^3.19.2"
